import {
  Flex,
  Container,
  Heading,
  Stack,
  Text,
  Button,
} from "@chakra-ui/react";
import { ArrowForwardIcon } from "@chakra-ui/icons";
// @ts-ignore
// import { Terminal } from "react-window-ui";
import { FaBook, FaDiscord, FaGithub, FaRocket } from "react-icons/fa";

import logo from "../assets/icon.png";
import ExternalLinkWithText from "./ExternalLinkWithText";
const demo = require("../assets/demo.mp4");

export default function CallToAction() {
  return (
    <Container maxW={"5xl"}>
      <Stack
        textAlign={"center"}
        align={"center"}
        spacing={{ base: 8, md: 10 }}
        py={{ base: 10, md: 15 }}
        style={{ paddingTop: "0 !important" }}
      >
        <img src={logo} alt="Logo" width={150} height={150} style={{
          animation: "bob 0.75s ease-in-out infinite alternate",
        }} />
        <style>
          {`
            @keyframes bob {
              from {
                transform: translateY(0);
              }
              to {
                transform: translateY(15px);
              }
            }
          `}
        </style>
        <Heading
          fontWeight={600}
          fontSize={{ base: "3xl", sm: "4xl", md: "6xl" }}
          lineHeight={"110%"}
        >
          <del>Develop</del>
          <ArrowForwardIcon /> Review Code
        </Heading>
        <Text color={"purple.400"} maxW={"3xl"} mt="10px !important">
          Spend time reviewing code generated by AI, not writing it
        </Text>
        <Stack spacing={6} direction={{ base: "column", md: "row" }} mb={{ base: "2rem !important", md: "1rem !important" }}>
          <Button
            color="white"
            p={8}
            colorScheme={"purple"}
            bg={"purple.400"}
            _hover={{ bg: "purple.600" }}
            onClick={() => window.open("https://github.com/apps/sweep-ai")}
            fontSize={"2xl"}
          >
            <FaGithub />&nbsp;&nbsp;Install Sweep
          </Button>
        </Stack>
        <ExternalLinkWithText
          href="https://github.com/apps/sweep-ai"
          color="purple.400"
          mt="0 !important"
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
          }}
        >
          <FaDiscord />&nbsp;&nbsp;Join our Discord
        </ExternalLinkWithText>
        <Flex w={"full"}>
          <Container width="100vw" boxShadow="0 0 80px #181818" p={0} maxWidth="full">
            <video src={demo} autoPlay muted loop playsInline>
              Your browser does not support the video tag.
            </video>
          </Container>
        </Flex>
      </Stack>
    </Container>
  );
}
